### ISSUE TITLE
CAD files for footprint switching?

### ISSUE THREAD

**Issue by KeLaiFu** [hugelton/Btns#1]
thanks for sharing this, it's certainly going to make many peoples access to grids much easier.

Would it be possible for you to share the CAD files so we can switch out the button footprint? I havnt been able to find those particular buttons in my part of the globe, but there's planty of similar alternatives.

Cheers!

**Comment by kurogedelic** [comment]
Added KiCAD file.
I used a very local Taiwanese switch so a global alternative would be welcome!

**Comment by KeLaiFu** [comment]
excellent, thanks!
I'm in China, so maybe not so global but more options are always better.

**Comment by dennisdebel** [comment]
> excellent, thanks! I'm in China, so maybe not so global but more options are always better.

Hi! I am in mainland as well and I was wondering what alternative switches you found and if you @KeLaiFu ever got around to footprint swapping?
